### ISSUE TITLE
Waveform collapses while zooming out

### ISSUE THREAD

**Issue by raulbehl** [Nic30/d3-wave#15]
Thank you for the wonderful tool. I was playing with it and ran into the following bug where the waveform suddenly collapses while zooming out. This also happens if drags towards time 0 (moving horizontal scroll bar towards right). I've attached a video which showcases this bug. I'd be happy to pick this up but would need some pointers on what could be going wrong!

https://user-images.githubusercontent.com/7036260/196024563-6b1d7e6f-7111-468c-9ea4-64bd344cd3eb.mov

**Comment by Nic30** [comment]
Hello @raulbehl ,
happens this also in https://github.com/Nic30/d3-wave/blob/master/examples/viewer.html ?
I am trying to ask if you do have some special setup or on. This may happen if there is some problem with the binding of zoom listeners.

Naturally I also think that this is my library I am just asking to make it sure before looking into it.

**Comment by Nic30** [comment]
About what can be wrong:
This library uses d3 zoom https://github.com/Nic30/d3-wave/blob/master/src/d3-wave.js#L71
Use is relatively standard use, however zoom implementation in d3 seems tricky to me.

**Comment by raulbehl** [comment]
> Hello @raulbehl ,
happens this also in https://github.com/Nic30/d3-wave/blob/master/examples/viewer.html ?

Yes, I found this using the `viewer.html` on the `master` branch. I've attached the json which you can use to reproduce it at your end too. 

JSON: https://gist.github.com/raulbehl/b7f26e3e44305d76fff8285a135aab71

**Comment by Nic30** [comment]
Can you try version from the git now?

**Comment by raulbehl** [comment]
Works like a charm. Thank you for the quick fix. Marking this as closed.
