### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by heyhexadecimal** [Nic30/d3-wave#21]
Hi @Nic30 , i appreciate your work, i want integrate d3-wave to my react to show waveforms in the browser. 
I am strugling to find a way how we integrate it with react, there is no documentation on npm and readme. 
Your help in this will be highly appreciated. 
Thanks

**Comment by Nic30** [comment]
Sorry for late response, were you able to find https://github.com/Nic30/d3-wave/blob/master/examples/viewer.html or were there another problems preventing you from using d3-wave.

:note: I tried to write this library in native react but it was too slow.

**Comment by heyhexadecimal** [comment]
Hey @Nic30 , Thanks for the reply. I sort it out.
